version: '3.9'

services:
  app1:
    build:
      context: ./app1
    ports:
      - "4000:4000"
    networks:
      - red1

  app2:
    build:
      context: ./app2
    ports:
      - "4001:4001"
    networks:
      - red1
    environment:
      - URL=app1
    #Especifica que la app2 debe iniciarse después de la app1
    depends_on:
      - app1

#Declara la red a la que se conectaran los contenedores
networks:
  red1:
    driver: bridge